### ISSUE TITLE
Duplicate line

### ISSUE THREAD

**Issue by Sophist-UK** [herewithme/simple-tags#27]
Not sure if it is a typo or not, but at line 6 is duplicated as line 7 in  simple-tags/inc/class.client.tagcloud.php.

**Comment by herewithme** [comment]
One line have dash and the second have underscore... 
Not the same ;)

**Comment by Sophist-UK** [comment]
Oh yes - so it is, so it is. 

My eyesight isn't what it once was, you know!!! {Cackley laugh}
